"""Postgres schema and connection helpers for HerdMaster."""

from __future__ import annotations

import hashlib
import os
import re
from pathlib import Path
from typing import Any

import psycopg
from psycopg import sql
from psycopg.rows import dict_row

SCHEMA_VERSION = 2

DEFAULT_DATABASE_URL = "postgresql://aop_dev:aop_dev_postgres_20260626@127.0.0.1:5432/aop"

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS agents (
    id                 TEXT PRIMARY KEY,
    label              TEXT NOT NULL,
    type               TEXT NOT NULL,
    role               TEXT NOT NULL,
    herdr_pane         TEXT,
    herdr_ws           TEXT,
    state              TEXT DEFAULT 'unknown',
    health             TEXT DEFAULT 'healthy',
    strengths          TEXT,
    avg_task_seconds   INTEGER,
    tasks_completed    INTEGER DEFAULT 0,
    last_heartbeat     TIMESTAMPTZ,
    last_output_hash   TEXT,
    created_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
    id                     TEXT PRIMARY KEY,
    name                   TEXT NOT NULL,
    scope                  TEXT NOT NULL,
    state                  TEXT DEFAULT 'submitted',
    complexity_tier        TEXT,
    deadline               TIMESTAMPTZ,
    squad_recommendation   TEXT,
    squad_approved         TEXT,
    eta_optimistic_hours   DOUBLE PRECISION,
    eta_expected_hours     DOUBLE PRECISION,
    eta_pessimistic_hours  DOUBLE PRECISION,
    eta_rationale          TEXT,
    orchestrator_analysis  TEXT,
    human_decision         TEXT,
    human_notes            TEXT,
    total_tasks            INTEGER DEFAULT 0,
    completed_tasks        INTEGER DEFAULT 0,
    failed_tasks           INTEGER DEFAULT 0,
    created_by             TEXT,
    approved_at            TIMESTAMPTZ,
    completed_at           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id                 TEXT PRIMARY KEY,
    project_id         TEXT REFERENCES projects(id),
    title              TEXT NOT NULL,
    description        TEXT,
    prompt             TEXT NOT NULL,
    state              TEXT DEFAULT 'queued',
    blocked_reason     TEXT,
    priority           INTEGER DEFAULT 2,
    assigned_to        TEXT REFERENCES agents(id),
    depends_on         TEXT,
    created_by         TEXT REFERENCES agents(id),
    dispatched_at      TIMESTAMPTZ,
    started_at         TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ,
    completed_by       TEXT REFERENCES agents(id),
    evidence           TEXT,
    duration_seconds   INTEGER,
    error_message      TEXT,
    retry_count        INTEGER DEFAULT 0,
    max_retries        INTEGER DEFAULT 3,
    timeout_seconds    INTEGER DEFAULT 1800,
    created_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    version            INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS task_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     TEXT NOT NULL REFERENCES tasks(id),
    agent_id    TEXT REFERENCES agents(id),
    event       TEXT NOT NULL,
    timestamp   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    evidence    TEXT,
    notes       TEXT
);

CREATE TABLE IF NOT EXISTS messages (
    id              TEXT PRIMARY KEY,
    type            TEXT NOT NULL,
    from_agent      TEXT REFERENCES agents(id),
    to_agent        TEXT,
    correlation_id  TEXT,
    payload         TEXT NOT NULL,
    delivered       BOOLEAN DEFAULT FALSE,
    acknowledged    BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS health_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    TEXT REFERENCES agents(id),
    event_type  TEXT NOT NULL,
    details     TEXT,
    created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       TEXT REFERENCES projects(id),
    complexity_tier  TEXT,
    total_tasks      INTEGER,
    agents_used      INTEGER,
    estimated_hours  DOUBLE PRECISION,
    actual_hours     DOUBLE PRECISION,
    accuracy_pct     DOUBLE PRECISION,
    completed_at     TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tasks_state ON tasks(state);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority, state);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_messages_to ON messages(to_agent, delivered);
CREATE INDEX IF NOT EXISTS idx_health_agent ON health_events(agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_projects_state ON projects(state);
CREATE INDEX IF NOT EXISTS idx_project_history_complexity ON project_history(complexity_tier);
CREATE INDEX IF NOT EXISTS idx_audit_task ON task_audit_log(task_id);
CREATE INDEX IF NOT EXISTS idx_audit_agent ON task_audit_log(agent_id, timestamp);
"""

SCHEMA_SQL = POSTGRES_SCHEMA_SQL


class PgCursor:
    """Small DB-API compatibility wrapper around a psycopg cursor."""

    def __init__(self, cursor: psycopg.Cursor[Any]) -> None:
        self._cursor = cursor

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def lastrowid(self) -> int | None:
        row = self.fetchone()
        if row is None:
            return None
        if isinstance(row, dict):
            return int(row.get("id")) if row.get("id") is not None else None
        return int(row[0])

    def fetchone(self) -> Any:
        return self._cursor.fetchone()

    def fetchall(self) -> list[Any]:
        return list(self._cursor.fetchall())

    def __iter__(self):
        return iter(self._cursor)


class PgConnection:
    """Connection facade preserving the subset of sqlite3 API used by HerdMaster."""

    def __init__(self, conn: psycopg.Connection[Any], schema_name: str) -> None:
        self._conn = conn
        self.schema_name = schema_name
        self._set_search_path()

    def _set_search_path(self) -> None:
        with self._conn.cursor() as cur:
            cur.execute(
                sql.SQL("SET search_path TO {}, public").format(sql.Identifier(self.schema_name))
            )

    def execute(self, query: str, params: Any = None) -> PgCursor:
        cur = self._conn.cursor()
        cur.execute(_translate_placeholders(query), params)
        return PgCursor(cur)

    def commit(self) -> None:
        self._conn.commit()
        self._set_search_path()

    def rollback(self) -> None:
        self._conn.rollback()
        self._set_search_path()

    def close(self) -> None:
        self._conn.close()


def _translate_placeholders(query: str) -> str:
    return query.replace("?", "%s")


def _schema_from_path(db_path: str | Path | None) -> str:
    if db_path is None:
        return os.environ.get("HERDMASTER_DB_SCHEMA", "herdmaster")
    value = str(db_path)
    if value.startswith(("postgresql://", "postgres://")):
        return os.environ.get("HERDMASTER_DB_SCHEMA", "herdmaster")
    digest = hashlib.sha1(value.encode("utf-8")).hexdigest()[:16]
    return f"hm_{digest}"


def _normalize_schema_name(schema_name: str) -> str:
    schema_name = schema_name.strip()
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", schema_name):
        raise ValueError(f"invalid Postgres schema name: {schema_name!r}")
    return schema_name


def _database_url(db_path: str | Path | None, database_url: str | None) -> str:
    if database_url:
        return database_url
    if db_path is not None and str(db_path).startswith(("postgresql://", "postgres://")):
        return str(db_path)
    return os.environ.get("DATABASE_URL") or DEFAULT_DATABASE_URL


def connect(
    db_path: str | Path | None = None,
    *,
    database_url: str | None = None,
    schema_name: str | None = None,
) -> PgConnection:
    """Open a Postgres connection for HerdMaster.

    ``db_path`` is retained for call-site compatibility. When it is not a
    Postgres URL, it is used only to derive an isolated schema name for tests.
    Runtime connections use ``DATABASE_URL`` or the local AOP Postgres default.
    """
    schema = _normalize_schema_name(schema_name or _schema_from_path(db_path))
    conn = psycopg.connect(_database_url(db_path, database_url), row_factory=dict_row)
    return PgConnection(conn, schema)


def init_db(conn: PgConnection) -> None:
    """Create the HerdMaster Postgres schema and indexes idempotently."""
    with conn._conn.cursor() as cur:
        cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(conn.schema_name)))
    conn.commit()
    conn.execute(POSTGRES_SCHEMA_SQL)
    conn.commit()
